### PR TITLE
Feature Add Horiontal Scroll Mode 

### PR DESCRIPTION
**Pull request by motty-mio2**
# Add Horizontal Scroll mode.
- Made Horizontal scroll based on infinite-scroll mode

### CODE REVIEW

**Comment by majora2007** [comment]
As discussed in discord, this needs some cleanup. I will try to work this in the next release (better search).

**Comment by motty-mio2** [comment]
Thank you very much.
I learn more about git and development.

**Comment by majora2007** [comment]
Don't worry, I didn't forget about this. I'm sorting all the remaining bugs from the Webtoon reader polishing, then I'll work on warping this effort up.

**Comment by motty-mio2** [comment]
Thank you. I'm looking forward to improved Webtoon reader mode.

**Comment by majora2007** [comment]
So you deleted your fork, so I'm going to have to manually port the changes over.

**Comment by majora2007** [comment]
So after porting the changes over, here are the following issues I see:

- [ ] Images are scaled to the height of the window. This means, it cannot be used for webtoons and HQ images will be scrunched.
- [ ] Using manual offset manipulation for scrolling is unadvised. 
- [ ] I'm unable to get the pages to layout properly, they just do 2 stacked horizontally
- [ ] Switching between Vertical to Horizontal has some skewing due to previously loaded pages having height already set.

I will work further on this to see what can be done, however, the first point which causes scaling is a pretty big issue.

**Comment by motty-mio2** [comment]
Sorry, I didn't understand github's usage. I re-uploaded my repositories and make pull-requests.

1. I set the image at the height of the window. I believe this is the behavior of side-scrolling comic book applications.
2. I see. I didn't come up a good idea for this...

I want to see the 3rd and 4th bugs. Could you send screen-shots please?

**Comment by majora2007** [comment]
My implementation is based on yours. I'm actually making some progress. 

I was able to make it like you showed on the discord. The main issue is really just the scaling. I need to do some testing on having 2 scrollbars. I will do some market research on how other readers approach this situation.

You don't have to re-raise a PR since I've already ported the changes in.

**Comment by motty-mio2** [comment]
Thank you so much.

**Comment by majora2007** [comment]
This story is almost done, I'm going to close out your PR (as mentioned earlier, I had to manually port your stuff into a new branch) . The story can be tracked here.
https://github.com/Kareadita/Kavita/pull/775

**Pull request closed without merging**
