### PR TITLE
Add middle-click functionality to various cards

### PR DESCRIPTION
**Pull request by acsellers**
# Added
- Added: Implemented a middle click event and handlers on the obvious places where users might want to open something in a new tab.

### CODE REVIEW

**Comment by majora2007** [comment]
This is too much code duplication. Instead, we should look at using anchors with target _blank. This way we can utilize existing code and url routes.

**Review by majora2007 — CHANGES_REQUESTED** [review]
This is too much code duplication. Instead, we should look at using anchors with target _blank on the cards or handling it internally in the card-item component. This way we can utilize existing code and url routes.

**Comment by majora2007** [comment]
Not sure if you're going to come back and update it. I'll put this in a future release and tackle it then with the way I purposed.

**Comment by Dimava** [comment]
Rather then do *anything* with middle-clicks it may be better to just do nothing and leave handling of everything except non-modified click to the browser default handlers - like <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>LMB</kbd> which has the default behaviour to open a link in a new foreground tab in most of browsers

**Comment by snickers2k** [comment]
never used a "middle" click for years :D how to even do it on a mac with trackpad? O_o

**Pull request closed without merging**
