### PR TITLE
Bugfix/base url in docker

### LINKED ISSUE #1900: Bug: BaseUrl does not work in all Docker environments
**Describe the bug**
The `BaseUrl` config is disabled in Docker environments where `OsInfo` detects that it's in a Docker environment. The initial Docker check was meant for disabling port changes in Docker environments, which is not useful as you're meant to use port mappings to change the port. Since the majority of config in `Configuration.cs` had the check, it ended up being copied over into the `BaseUrl` getters and setters, even though it is not relevant.

**To Reproduce**
1. Spin up a Docker instance on a Windows/Unraid host
2. Note that the BaseUrl feature does not do anything
3. Spin up a Docker instance on an Ubuntu (22.04) host
4. Note that the BaseUrl feature works

**Expected behavior**
BaseUrl feature should work on any Docker image regardless of host

**Additional context**
Discussion in: https://github.com/Kareadita/Kavita/pull/1824
See also: https://github.com/Kareadita/Kavita/pull/1880

Possible tangential bug is that `OsInfo` detects Docker in Ubuntu as Linux rather than Docker

### PR DESCRIPTION
**Pull request by Yidna**
# Fixed
- Fixed: Fixed a bug where BaseUrl did not work in all Docker environments (Fixes #1900)

### CODE REVIEW

**Comment by majora2007** [comment]
@Kizaing can you give this a once over and if it's good, we can merge it.

**Comment by therobbiedavis** [comment]
> @Kizaing can you give this a once over and if it's good, we can merge it. 

Hey Chris, can you validate on unraid or an OS outside of Ubuntu? It seems like docker on ubuntu is showing up as Linux instead of docker.

**Comment by Kizaing** [comment]
Yeah for sure, I'll validate it on Unraid and other non Ubuntu linux OS's and get back with my results

**Comment by Yidna** [comment]
Any updates?

**Comment by Kizaing** [comment]
Apologies on the long time, life got a bit busy haha

Everything seems to be working I tested on UNRAID, however OPDS appears to be broken when using Base URL. Tachiyomi works fine since it's using the API, but I tried regular OPDS with both Librera and Moon+ Reader and for both the /kavita/ base url was removed when connecting.

**Comment by majora2007** [comment]
I'll take over the OPDS implementation, since it was missed in the original PR.

**Comment by fawqsir** [comment]
I am using docker image kizaing/kavita:nightly-0.7.1.39 .  How can I change the base url so that I can access from example.com/kavita/? is there an environtment variable? is there a command line option? I cant seem to find any documentation.

Could line 12 in [Configuration.cs](https://github.com/Kareadita/Kavita/blob/develop/Kavita.Common/Configuration.cs)
`public const string DefaultBaseUrl = "/";`

`public const string DefaultBaseUrl = "$BASE_URL/";`

**Comment by majora2007** [comment]
@fawqsir you just update it in the UI and restart

**Pull request merged**
