### PR TITLE
Avoid multiple concurrent extractions of the same archive v2

### LINKED ISSUE #2494: Tachiyomi volume downloads sometimes missing pages
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
When using Tachiyomi, I use the download button to save a local copy of a manga volume to my phone or tablet for offline reading later. Sometimes the downloaded volume is missing pages, and it seems to be random if it happens at all and which pages it happens to, but most often it is the cover or one of the first few pages. To make up for the missing pages, tachiyomi then shows some other pages duplicated, so that the total page count of the volume remains the same. For example, I would expect a volume to show pages in this order: Cover, page 1, page 2, page 3, page 4. But there's a random chance I will see this instead: Page 4, Page 5, Page 3, Page 3, Page 4. This happens on both my smartphone and my fire tablet, but happens much more often on my tablet.

**To Reproduce**
1. Connect Tachiyomi app to Kavita using the OPDS url
2. Pick any manga volume from the library and "download to local device"
3. Read the downloaded volume
4. Sometimes pages are missing/jumbled, it's random

**Expected behavior**
Volume should extract correctly every time without missing pages.

**Kavita Server:**
 - Raspberry Pi 4b
 - Docker image lscr.io/linuxserver/kavita:latest
 - Current version: 0.7.11.2

**Smartphone:**
 - Device: Galaxy S21
 - OS: Android
 - Tachiyomi 0.14.7
 - Kavita Extension 1.4.11

**Tablet:**
 - Device: Kindle Fire
 - OS: Fire OS
 - Tachiyomi 0.14.7
 - Kavita Extension 1.4.11

**Additional context**
I only just started using Tachiyomi about a half a year ago and this issue has always been present. I only just now decided to try and find a fix for this issue, and after reaching out in the discord I was suggested to create this issue as this apparently is not a well known issue.

I captured this error in the kavita logs while testing the issue recently:

```
[Kavita] [2023-12-11 10:27:14.658 -05:00  94] [Warning] API.Services.ArchiveService [ExtractArchive] There was a problem extracting /manga/Choujin X/Choujin X v04 (2023) (Digital) (1r0n).cbz to /app/kavita/config/cache/8242/
System.IO.IOException: The process cannot access the file '/app/kavita/config/cache/8242/Choujin X - c022 (v04) - p002 [VIZ Media] [Digital] [1r0n].png' because it is being used by another process.
```

Based on the error message, my layman assumption is Kavita is attempting to do multiple parallel things to the cbz file while tachiyomi is downloading it and Kavita is extracting it to its local cache at the same time. Sometimes there is a missing page from the cache due to the error, but more pages will be jumbled on Tachiyomi than just the one missing from cache.

While discussing this issue in the discord I was told this sounds related to a similar issue: #2478

### LINKED ISSUE #2604: Chapters starting halfway through and repeating pages
### What happened?

Chapters starting with different pages as page 1, with the same page repeating multiple times at the end.
For example: a 20 page chapter starts with page 5 (005.png) as the "first page" would have the last page (020.png) show up on page 16, repeating until the end of the chapter.
Steps I took:
1. Navigate to the Kavita web UI
2. Select the series I want to read
3. Select the chapter I want to read
4. Encounter issue

### What did you expect?

The pages to be in order with no repeats

### Version

0.7.12.0 Server
1.4.13 Tachiyomi Extension

### What OS is Kavita being run on?

Docker

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Firefox

### Relevant log output

_No response_

### Additional Notes

Broken chapters accompanied by 400 Error
Chapters are fine when the files are read locally with something like CDisplay, or opened in an archive viewer.
Doesn't happen with every chapter archive.
Happens in Tachiyomi too

### PR DESCRIPTION
**Pull request by SamuelBMartins**
# Fixed
- Fixed: Fixed a bug where multiple extractions of the same archive would start concurrently and create file system problems (Fixes #2494 and fixes #2604)

### CODE REVIEW

**Comment by SamuelBMartins** [comment]
This is a continuation of the PR #2840.

This time I used an `ConcurrentDictionary<int, SemaphoreSlim>` so that every chapter uses a different Semaphore. The dictionary keeps every Semaphore ever used in memory since the semaphore is needed not only for creating the cache but also checking if the cache exists in successive request. I have another branch [bugfix/concurrent-extraction2-2](https://github.com/SamuelBMartins/Kavita/tree/bugfix/concurrent-extraction2-2) where I try to keep the number of entries in the dictionary low. However, I'm not sure this alternative is better since for each page requested, even if already cached, I need to create a new semaphore.

@majora2007 Can you check if you notice a slowdown with this solution? If there are some automated benchmarks I can run them myself.

**Comment by majora2007** [comment]
Hey, sorry haven't gotten around to this. Been pretty swamped irl. There is another PR from Robbie with reader changes. Going to combine these and deploy them to my prod instance to give a good shakeout this week.

**Comment by majora2007** [comment]
Looking good so far, nothing stood out. I yet again manually merged this into another branch that will be merged, then I will close this PR.

**Comment by majora2007** [comment]
This was merged here:
https://github.com/Kareadita/Kavita/pull/2960

**Pull request closed without merging**
