### PR TITLE
Fix the issue of not being able to navigate to the next/previous chapter while scrolling.

### PR DESCRIPTION
**Pull request by charles7668**
# Fixed
- Fixed: Fix the issue of not being able to navigate to the next/previous chapter while scrolling. (#2352)

before
firefox_WYy1zotZHR
after
firefox_0NpFYj9UMx

### CODE REVIEW

**Comment by majora2007** [comment]
I have another branch that I've done significant work on the webtoon reader on. I'll test this then merge and test it. 

What browser are you testing on? iOS has significant issues with the webtoon reader as a whole, hence me taking a stab at fixing it up. Branch is: bugfix/webtoon-reader if you want to play with your changes in there.

**Comment by charles7668** [comment]
> I have another branch that I've done significant work on the webtoon reader on. I'll test this then merge and test it.
> 
> What browser are you testing on? iOS has significant issues with the webtoon reader as a whole, hence me taking a stab at fixing it up. Branch is: bugfix/webtoon-reader if you want to play with your changes in there.

I tested this in Firefox and Edge browsers, both in normal mode and device mode.

I also tested the 'bugfix/webtoon-reader' branch, but it seems to exhibit different behavior compared to the 'develop' branch. Therefore, I believe this pull request may not be suitable for the 'bugfix/webtoon-reader' branch. If you are working on fixing the webtoon reader, please consider closing this pull request.

**Comment by majora2007** [comment]
I tried this against my normal code and it wasn't working well. 

What I did was scrolled to end, scrolled into next chapter. 
Scrolled down, then up into previous. It will load on last page of chapter 1.
I then tried to scroll down again and the continuous spacer never generated so i could scroll down into next chapter.

**Comment by majora2007** [comment]
I'm going to close this since I switched the bottom cont scroller to use intersection observable.

**Pull request closed without merging**
