### PR TITLE
[Docker] Make Kavita executable at Build time instead of Runtime 

### LINKED ISSUE #1889: Entryfile.sh tries to set chmod +x on every run
**Describe the bug**
Line 27 of the entryfile.sh tries to make the executable runnable every time the docker container starts. If the docker image just shipped with that change by default it wouldn't be necessary to do it at launch each time. Moving it to the dockerfile I think makes more sense. 

This would also resolve the issues with errors in the logs each time the container is started 
```
chmod: changing permissions of 'Kavita': Operation not permitted
```

**To Reproduce**
1. Launch the container in docker

**Expected behavior**
The docker image should ship with the file having the right permissions from the start. 

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Any
 - Version: v0.7.1.27

### PR DESCRIPTION
**Pull request by stavros-k**
# Fixed
- Fixed: Makes Kavita program and the entrypoint script executable, which removes the need to do that on every startup of the container, additionally is one step closer (still needs other changes) to potentially make the docker image run as rootless. (Fixes: https://github.com/Kareadita/Kavita/issues/1889)

### CODE REVIEW

**Comment by majora2007** [comment]
Please include a PR body like the template requests and information why this is needed.

**Comment by stavros-k** [comment]
> Please include a PR body like the template requests and information why this is needed.

Done, Sorry, github.dev bypasses the template when opening PR from there.

**Comment by majora2007** [comment]
Thanks. I'm on holiday but I'll take a look afterwards.

**Comment by Kizaing** [comment]
I looked it over, looks good to me 👍

**Review by Kizaing — APPROVED** [review]

**Pull request merged**
