### PR TITLE
Use new Queryable extension method DoOrderBy() for cleaner code

### PR DESCRIPTION
**Pull request by senpai-notices**
# Developer
- Changed: Refactor SeriesSort and BookmarkSort to use Queryable extension method DoOrderBy() for cleaner code
- Changed: Refactor SeriesRepository.CreateFilteredSearchQueryable() to use Queryable extension method DoOrderBy() for cleaner code

### CODE REVIEW

**Comment by senpai-notices** [comment]
Hey @majora2007 - would like your thoughts on this to see if this is an appropriate abstraction.

**Comment by majora2007** [comment]
This does make the code slightly cleaner. It would be wise to apply this to the old v1 implementation as well. 

If you're interested in helping out in the codebase, it would be helpful if we could chat more directly. Hit me up on discord in the server please.

**Comment by majora2007** [comment]
Also the changelog for the PR, while you're is good for development, they are user-focused. A user wont understand this code changes, so you can use # Developer and put your Change in there.

**Comment by senpai-notices** [comment]
Thanks for the feedback @majora2007.

I've applied it to the v1 and will use # Developer for the changelog.

Sure, I'll be in touch on Discord.

**Review by majora2007 — APPROVED** [review]
I'll just do a shakeout in a bit then merge this in.

**Pull request merged**
